[phases.setup]
nixPkgs = ["nodejs_22", "python3", "python3Packages.pip", "yt-dlp", "gnumake", "gcc", "ffmpeg"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "pip install --break-system-packages --upgrade yt-dlp && echo \"yt-dlp: $(which yt-dlp) $(yt-dlp --version)\" && npm start"
