[phases.setup]
nixPkgs = ["nodejs_22", "python3", "python3Packages.pip", "gnumake", "gcc", "ffmpeg"]

[phases.install]
cmds = ["pip install --break-system-packages yt-dlp", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
